task/01-setup
volodymyr-kravchenko-moc/fe-react-2024 pull request #1
Opened 2024-04-26 14:23 UTC by volodymyr-kravchenko-moc

**Acceptance criteria for 1**

- [x] Mentor is added to pr
- [x] AC copied to pr description
- [x] link to deployed version added to pr
- [x] About block (text and image) added to the main page
- [x] On the widths 390px and 1280px, the site layout corresponds to the design

**Acceptance criteria for 1***

- [x] Created separate component About
- [x] Its styles added to .module.css
- [x] For App.tsx styles moved to App.module.css

https://volodymyr-kravchenko-moc.github.io/fe-react-2024/

2024-04-27 09:28 UTC, vladyslav-yermolin-moc commented
Hey, @volodymyr-kravchenko-moc, thanks for your work.
I will check it during the day

2024-04-27 14:02 UTC, vladyslav-yermolin-moc requested changes
Good job 👍

2024-04-27 14:02 UTC, vladyslav-yermolin-moc commented on src/components/about/About.module.css
> +  flex: 1 0 auto;
I suggest you use full properties names, not the short description:
```css
flex-grow: 1;
flex-shrink 0;
flex-basis: auto;
```

2024-04-27 14:02 UTC, vladyslav-yermolin-moc commented on src/components/about/About.module.css
> +  flex: 1 0 auto;
Another solution: use `width` of the image, to set image's width, not the flex props of its container.

2024-04-27 14:02 UTC, vladyslav-yermolin-moc commented on src/components/about/About.module.css
> +  align-self: center;
```suggestion

```

2024-04-27 14:02 UTC, vladyslav-yermolin-moc commented on src/components/about/About.component.tsx
> +        <section className={styles.wrapper}>
I think, would be better to add description and image to one flex container and align its items by top side. Now you have unwanted indentation
<img width="1271" alt="image" src="https://github.com/volodymyr-kravchenko-moc/fe-react-2024/assets/98031768/dd50af4e-fa0d-439c-a66e-836e474f04ca">

2024-04-27 14:02 UTC, vladyslav-yermolin-moc commented on src/components/about/About.component.tsx
> +            <AboutDescriptionComponent />
Do you really need a separate component for this text? Will you plan to reuse it, or, maybe it has some logic, which you like to encapsulate?
This is just a text🤷‍♂️

2024-04-27 14:02 UTC, vladyslav-yermolin-moc commented on src/components/about/description/AboutDescription.component.tsx
> +            Hi! My name is [Name] and I&apos;m a Junior Frontend Developer. I am already familiar with main Web Technologies like React,
Please add some name. We plan, hre you can add your name and photo. If you don't like this idea, just add some one.

2024-04-27 14:02 UTC, vladyslav-yermolin-moc commented on src/components/about/description/AboutDescription.component.tsx
> +        <p>This page was developed during the course &apos;Intro to React&apos; from Masters Academy in 2024.</p>
Please add a link as on the design
![image](https://github.com/volodymyr-kravchenko-moc/fe-react-2024/assets/98031768/79b8f550-8290-4b2f-86d5-6d29c4e0321e)

2024-04-27 14:02 UTC, vladyslav-yermolin-moc commented on src/components/about/description/AboutDescription.component.tsx
> +        <p>You can contact me via [social network name] and check out my GitHub.</p>
Please add some links. Your social networks or any other links.
![image](https://github.com/volodymyr-kravchenko-moc/fe-react-2024/assets/98031768/71062309-2f90-4461-9666-f28d39817b76)
Example from your colleague 
<img width="746" alt="image" src="https://github.com/volodymyr-kravchenko-moc/fe-react-2024/assets/98031768/7e284804-9696-4dee-b85e-9626c556627e">

2024-04-27 14:02 UTC, vladyslav-yermolin-moc commented on src/components/about/About.module.css
> +  border-radius: 20px;
please correct the radius according to design: 30 for mobile, 40 for desktop

2024-04-27 14:02 UTC, vladyslav-yermolin-moc commented on Dockerfile
> +FROM node:20.9.0
cool😎

2024-04-27 14:02 UTC, vladyslav-yermolin-moc commented on src/components/about/description/AboutDescription.module.css
> +  flex: 1 1 auto;
This code does nothing, Would be better not to add it.

2024-04-27 14:02 UTC, vladyslav-yermolin-moc commented on src/components/about/description/AboutDescription.module.css
> +  height: 100vh;
You have used 100vh for the main container already. 
here I suggest to dance from the parent size
```suggestion
  height: 100%;
```

2024-04-27 14:02 UTC, vladyslav-yermolin-moc commented on src/components/about/About.component.tsx
> +import about from '@/assets/about/index.png';
Please add some decent names. Like
```suggestion
import aboutImg from '@/assets/about/about-photo.png';
```

2024-04-30 12:25 UTC, volodymyr-kravchenko-moc commented on src/components/about/description/AboutDescription.module.css
> +  flex: 1 1 auto;
Fixed

2024-04-30 12:25 UTC, volodymyr-kravchenko-moc commented on src/components/about/About.component.tsx
> +import about from '@/assets/about/index.png';
Fixed

2024-04-30 12:25 UTC, volodymyr-kravchenko-moc commented on src/components/about/About.module.css
> +  border-radius: 20px;
Fixed

2024-04-30 12:25 UTC, volodymyr-kravchenko-moc commented on src/components/about/About.component.tsx
> +            <AboutDescriptionComponent />
No, I just used it as a way to group elements
I realized it's not okay, so I removed the component :)

2024-04-30 12:25 UTC, volodymyr-kravchenko-moc commented on src/components/about/description/AboutDescription.module.css
> +  height: 100vh;
Fixed

2024-04-30 12:25 UTC, volodymyr-kravchenko-moc commented on Dockerfile
> +FROM node:20.9.0
Thanks :)

2024-04-30 12:25 UTC, volodymyr-kravchenko-moc commented on src/components/about/description/AboutDescription.component.tsx
> +        <p>You can contact me via [social network name] and check out my GitHub.</p>
Fixed

2024-04-30 12:25 UTC, volodymyr-kravchenko-moc commented on src/components/about/description/AboutDescription.component.tsx
> +        <p>This page was developed during the course &apos;Intro to React&apos; from Masters Academy in 2024.</p>
Fixed

2024-04-30 12:25 UTC, volodymyr-kravchenko-moc commented on src/components/about/description/AboutDescription.component.tsx
> +            Hi! My name is [Name] and I&apos;m a Junior Frontend Developer. I am already familiar with main Web Technologies like React,
Fixed

2024-04-30 12:25 UTC, volodymyr-kravchenko-moc commented on src/components/about/About.component.tsx
> +        <section className={styles.wrapper}>
Fixed

2024-04-30 12:25 UTC, volodymyr-kravchenko-moc commented on src/components/about/About.module.css
> +  flex: 1 0 auto;
Outdated

2024-04-30 14:34 UTC, vladyslav-yermolin-moc approved these changes
Nice start 👍

2024-04-30 14:34 UTC, merged