task/04-styling
volodymyr-kravchenko-moc/fe-react-2024 pull request #4
Opened 2024-07-07 18:32 UTC by volodymyr-kravchenko-moc

2024-07-15 16:22 UTC, vladyslav-yermolin-moc commented
Please add active states for theme buttons. E.g. for this moment, button of light theme should be active
<img width="960" alt="image" src="https://github.com/user-attachments/assets/430e0ed2-0892-424b-a9bf-f4643e35b7f8">

2024-07-15 16:58 UTC, vladyslav-yermolin-moc requested changes

2024-07-15 16:58 UTC, vladyslav-yermolin-moc commented on src/components/searchBar/searchBar.module.css
> +  .searchBar {
I would suggest that you change the layout of the filters earlier. Now before the 768 breakpoint, you layout is broken a bit 
<img width="790" alt="image" src="https://github.com/user-attachments/assets/4d1e7559-c650-4851-ae14-f0ecf35eaf51">

2024-07-15 16:58 UTC, vladyslav-yermolin-moc commented on src/components/productCard/productCard.module.css
Please correct the color of the product border and the color of active filter
<img width="1026" alt="image" src="https://github.com/user-attachments/assets/0bdc11d1-a770-4fae-b81e-a872e0a852dd">

2024-07-15 16:58 UTC, vladyslav-yermolin-moc commented on src/components/searchBar/SearchBar.component.tsx
> +                            </button>
You can move this logic to some function or even a separate component. After, here in template you can utilize this method or component. It would be cleaner
```suggestion
const getCategoryButton = (category) => {
                        const buttonStyles =
                            category === selectedCategory
                                ? `${styles.activeCategoryButton} ${styles.categoryButton}`
                                : styles.categoryButton;
                        return (
                            <button
                                key={category}
                                className={buttonStyles}
                                onClick={() => {
                                    setSelectedCategory(category);
                                }}
                            >
                                {category}
                            </button>
                            }
                            
.....
{categories.map(getCategoryButton)}
```

2024-07-15 16:58 UTC, vladyslav-yermolin-moc commented on src/components/searchBar/sortingDropDown/SortingDropDown.component.tsx
> +    const toggleDropdown = () => {
If you like, you can add a  typical logic to close dropdown on `Esc` and click outside of dropdown

2024-07-15 16:58 UTC, vladyslav-yermolin-moc commented on src/components/searchBar/sortingDropDown/SortingDropDown.component.tsx
> +                        <div onClick={() => handleSortChange('Price (High - Low)')} className={styles.dropdownItem}>
Here you can reuse an approach with categories buttons:
- make an array of them
- make a method/ component for single element
- iterate this array to render

2024-07-17 20:25 UTC, volodymyr-kravchenko-moc commented on src/components/productCard/productCard.module.css
Fixed. Thanks

2024-07-24 20:44 UTC, volodymyr-kravchenko-moc commented on src/components/searchBar/searchBar.module.css
> +  .searchBar {
Fixed, thanks

2024-07-24 20:45 UTC, volodymyr-kravchenko-moc commented on src/components/searchBar/SearchBar.component.tsx
> +                            </button>
good point, thank you. fixed

2024-07-24 20:46 UTC, volodymyr-kravchenko-moc commented on src/components/searchBar/sortingDropDown/SortingDropDown.component.tsx
> +    const toggleDropdown = () => {
Good advice, implemented, thank you.

2024-07-24 20:47 UTC, volodymyr-kravchenko-moc commented on src/components/searchBar/sortingDropDown/SortingDropDown.component.tsx
> +                        <div onClick={() => handleSortChange('Price (High - Low)')} className={styles.dropdownItem}>
fixed too, thanks

2024-07-29 16:15 UTC, vladyslav-yermolin-moc approved these changes
Good work!

2024-07-29 16:15 UTC, merged